name: ModReq
version: @project.version@
main: uk.co.notnull.modreq.ModReq
author: Jim (AnEnragedPigeon)
api-version: '1.20.6'
description: File moderator requests.
softdepend:
  - SuperVanish
  - PremiumVanish
